#pragma once

enum StateName {
    STATE_RCB_MOTOR,
    STATE_NACELLE_SERVO,
    STATE_LIFT_SERVO,
    STATE_LIFT_MOTOR,
    STATE_LEVEL_SERVO,
    STATE_STEPPER1,
    STATE_STEPPER2,
    STATE_STEPPER3,
    STATE_DELAY,
    STATE_PRELAUNCH,
    STATE_LAUNCH_DETECTION,
    STATE_APOGEE_DETECTION,
    STATE_LANDING_DETECTION,
    END_STATE,
};

enum EventName {
    INITIALIZE,
    BASIC_SWIVEL,
    BASIC_ROTATE,
    BASIC_SERVO,
    DELAY_1_SECOND,
    DELAY,
    TERMINATE,
    PRELAUNCH_COMPLETE,
    LAUNCH_DETECTED,
    APOGEE_DETECTED,
    LANDING_DETECTED
};